# see https://docs.python.org/3/library/logging.config.html#logging-config-dictschema

version: 1

loggers:
  '':
    handlers: [ all_file ]
    level: INFO
  deadapi: { handlers: [ api_file ] }
  deadaux: { handlers: [ aux_file ] }
  deadsrv: { handlers: [ srv_file ] }

handlers:
  all_file:
    class: logging.handlers.RotatingFileHandler
    formatter: f
    level: WARNING
    filename: logs/error.log
    maxBytes: 100000000  # 100M
    backupCount: 3
  aux_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: f
    level: INFO
    filename: logs/deadaux.log
    backupCount: 7
    when: midnight
  api_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: f
    level: INFO
    filename: logs/deadapi.log
    backupCount: 7
    when: midnight
  srv_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: f
    level: INFO
    filename: logs/deadsrv.log
    backupCount: 7
    when: midnight

formatters:
  f:
    (): 'common.utils.logging.Formatter'
    format: '%(asctime)s %(levelname)s - %(name)s - %(message)s'

disable_existing_loggers: False
